name: picker_pro_max_ultra
description: A powerful media picker plugin for Flutter.
version: 1.0.1
repository: https://github.com/kasimVora/picker_pro_max_ultra.git
homepage: https://github.com/kasimVora/picker_pro_max_ultra

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  photo_manager: ^3.6.4
  plugin_platform_interface: ^2.0.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.picker
        pluginClass: PickerPlugin
      ios:
        pluginClass: PickerPlugin


