name: picker_pro_max_ultra
description: Advanced media picker for Flutter with support for images, videos, camera capture, documents, and multi-selection.
version: 2.0.2
repository: https://github.com/kasimVora/picker_pro_max_ultra.git
homepage: https://github.com/kasimVora/picker_pro_max_ultra

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  photo_manager: ^3.6.4
  skeletonizer: ^1.4.3
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.picker
        pluginClass: PickerPlugin
      ios:
        pluginClass: PickerPlugin


